### PR TITLE
Implement components

### PR DESCRIPTION
**Pull request by hacst**
With these changes LogikSim gains a notion of components as logical building blocks of a circuit as well as the machinery to instantiate, manipulate and observe them.

### CODE REVIEW

**Comment by hacst** [comment]
@chris- Hi. You probably want to take a look at these changes and see if you agree with the general direction. The concepts are quite similar to what we were working before with small twists here and there. In the current state at least basic simulation functionality ought to be working though the interface isn't complete yet and I'm pretty sure there's still breakage in many places. For front-end work this should at least give us something to work with and remove the blockage we currently have there.

**Comment by christianbrugger** [comment]
I will have a look

**Comment by hacst** [comment]
From my POV this PR is ready to be merged. With the last commit it now contains everything I had in mind (and a bit more ;) ). Feel free to merge it after review. Unless of course you have anything you want to have changed before it lands ;)

**Comment by chris-** [comment]
Awesome, great work!

While reviewing the code I recognized a lot of concepts from the Python implementation. At this point we can assume that the circuits are static, I see how this made everything much easier.

Looking forward to see the simulation engine in action.

**Pull request merged**
